"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import NavSection from "./components/sidebar/NavSection";
import Tab from "./components/sidebar/Tab";
import Accordion from "./components/sidebar/Accordion";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// Metadata cannot be exported from client components.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [selectedItem, setSelectedItem] = useState("Dashboard");

  const handleMenuClick = (itemName: string) => {
    setSelectedItem(itemName);
  };

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
          <Header />
          <div style={{ display: 'flex', flexGrow: 1, overflow: 'hidden' }}>
            <Sidebar>
              <NavSection title="Main">
                <Tab onClick={() => handleMenuClick('Dashboard')}>Dashboard</Tab>
                <Tab onClick={() => handleMenuClick('Analytics')}>Analytics</Tab>
              </NavSection>
              <NavSection title="Management">
                <Accordion title="Users">
                <div onClick={() => handleMenuClick('All Users')}>All Users</div>
                <div onClick={() => handleMenuClick('Permissions')}>Permissions</div>
              </Accordion>
              </NavSection>
              <NavSection title="Settings">
                <Tab onClick={() => handleMenuClick('General')}>General</Tab>
                <Tab onClick={() => handleMenuClick('Billing')}>Billing</Tab>
              </NavSection>
            </Sidebar>
            <main style={{ flexGrow: 1, padding: '20px', overflowY: 'auto' }}>
              <h1>{selectedItem}</h1>
              {children}
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
