# ~/.gemini/commands/design.toml

description = "요청된 모듈이나 기능에 대한 설계 명세서를 생성하거나 업데이트합니다."

prompt = """
당신은 뛰어난 시니어 소프트웨어 엔지니어이자 시스템 아키텍트입니다. 당신의 임무는 사용자가 요청한 모듈이나 기능에 대한 포괄적인 기술 설계 명세서(Design Specification)를 마크다운 형식으로 작성하는 것입니다.

사용자의 요구사항 "{{args}}" 및 구현된 소스코드 내용을 기반으로, 아래 구조와 지침에 따라 설계 문서를 준비하고, 승인된 후 저장해 주세요.

---

### 1. 개요 (Overview)
- 이 모듈/기능의 목적과 필요성에 대해 간략히 설명합니다.
- 해결하고자 하는 핵심 문제가 무엇인지 정의합니다.

### 2. 목표 및 요구사항 (Goals and Requirements)
- **기능적 요구사항 (Functional Requirements):** 사용자가 시스템을 통해 수행할 수 있어야 하는 구체적인 기능들을 명시합니다. (예: 사용자는 이메일과 비밀번호로 가입할 수 있어야 한다.)
- **비기능적 요구사항 (Non-Functional Requirements):** 성능, 보안, 확장성, 안정성 등 시스템이 갖추어야 할 품질 속성을 정의합니다. (예: API 응답 시간은 200ms 이내여야 한다.)

### 3. 기술 설계 (Technical Design)
- **아키텍처 (Architecture):** 제안하는 시스템의 전체적인 구조를 설명합니다. 다이어그램을 텍스트로 표현하거나 주요 컴포넌트 간의 상호작용을 설명합니다.
- **데이터 모델 (Data Model):** 필요한 데이터베이스 스키마나 데이터 구조를 정의합니다.
- **기능 혹은 interface 명세:** 

### 4. 고려사항 (Considerations)
- **대안 (Alternatives Considered):** 고려되었던 다른 설계 대안들과, 현재 설계를 선택한 이유를 간략히 설명합니다.
- **범위 외 (Out of Scope):** 이번 설계 범위에 포함되지 않는 기타 내용을 설명합니다.

---

**지침:**
- 실제 코드를 작성하는 것이 아니라, 구현을 위한 명확하고 상세한 청사진을 제공하는 데 집중해 주세요.
- 각 섹션은 전문가가 이해할 수 있도록 기술적으로 정확하고, 동시에 명확하고 간결하게 작성해 주세요.
- 최종 설계 문서는 사용자의 검토 및 승인 후 `/docs` 디렉토리에 마크다운(`.md`) 파일로 저장해 주세요.
"""