
import { Challenge, AIMessage } from './types';

export const CHALLENGES: Challenge[] = [
  {
    id: "1",
    title: "고요한 마음 30일",
    subtitle: "매일 명상으로 스트레스 줄이기",
    description: "매일 10분간의 명상 세션을 통해 마음의 평화를 찾고 집중력을 높이세요. 이 도전은 꾸준한 명상 습관을 형성하여 내면의 안정과 정신적 명료함을 찾는 데 도움을 줄 것입니다.",
    image: "https://picsum.photos/seed/mindfulness/600/400",
    category: "마음챙김",
    isUpcoming: false,
  },
  {
    id: "2",
    title: "매일 30분 운동 챌린지",
    subtitle: "건강한 습관 만들기",
    description: "어떤 운동이든 매일 30분씩 꾸준히 하여 체력을 증진하고 활력을 되찾으세요. 조깅, 요가, 홈 트레이닝 등 원하는 활동으로 건강한 라이프스타일을 만들어보세요.",
    image: "https://picsum.photos/seed/exercise/600/400",
    category: "운동",
    isUpcoming: false,
  },
  {
    id: "3",
    title: "한 달에 책 4권 읽기",
    subtitle: "지식의 지평을 넓히세요",
    description: "한 주에 한 권씩, 다양한 분야의 책을 읽으며 새로운 지식과 영감을 얻어보세요. 소설, 비문학, 자기계발 등 장르에 구애받지 않고 독서의 즐거움을 느껴보세요.",
    image: "https://picsum.photos/seed/reading/600/400",
    category: "독서",
    isUpcoming: false,
  },
  {
    id: "4",
    title: "알고리즘 마스터",
    subtitle: "매일 코딩 문제 풀기",
    description: "매일 최소 한 개의 알고리즘 문제를 풀며 코딩 실력과 문제 해결 능력을 향상시키세요. LeetCode, HackerRank 등 다양한 플랫폼을 활용하여 실력을 키워나갑니다.",
    image: "https://picsum.photos/seed/coding/600/400",
    category: "코딩",
    isUpcoming: false,
  },
  {
    id: "5",
    title: "미라클 모닝 챌린지",
    subtitle: "아침 6시 기상하기",
    description: "하루를 더 일찍 시작하여 나만의 시간을 확보하고 생산성을 극대화하세요. 아침 명상, 독서, 운동 등으로 하루를 활기차게 시작하는 습관을 만듭니다.",
    image: "https://picsum.photos/seed/morning/600/400",
    category: "새벽 기상",
    isUpcoming: false,
  },
  {
    id: "6",
    title: "수분 충전! 하루 2L",
    subtitle: "매일 물 2리터 마시기",
    description: "충분한 수분 섭취로 건강한 신체와 맑은 피부를 유지하세요. 하루 동안 꾸준히 물을 마시는 습관을 들여 몸의 신진대사를 활발하게 만듭니다.",
    image: "https://picsum.photos/seed/water/600/400",
    category: "물 마시기",
    isUpcoming: false,
  },
  {
    id: "7",
    title: "외국어 정복 프로젝트",
    subtitle: "매일 20분 외국어 공부",
    description: "새로운 언어를 배우며 다른 문화를 이해하고 소통의 폭을 넓혀보세요. 매일 꾸준한 학습으로 언어 능력을 향상시키고 새로운 기회를 만들어보세요.",
    image: "https://picsum.photos/seed/language/600/400",
    category: "언어 학습",
    isUpcoming: false,
  },
  {
    id: "8",
    title: "하루 세 가지 감사 일기",
    subtitle: "긍정적인 마음 갖기",
    description: "매일 잠들기 전, 하루 동안 감사했던 세 가지 일을 기록하며 긍정적인 태도를 길러요. 작은 것에도 감사하는 마음을 통해 삶의 만족도를 높일 수 있습니다.",
    image: "https://picsum.photos/seed/gratitude/600/400",
    category: "감사 일기",
    isUpcoming: false,
  },
  {
    id: "9",
    title: "재정적 자유 얻기",
    subtitle: "현명한 저축과 투자",
    description: "매일 10분간의 명상 세션을 통해 마음의 평화를 찾고 집중력을 높이세요.",
    image: "https://picsum.photos/seed/finance/600/400",
    category: "재정 관리",
    isUpcoming: true,
  },
  {
    id: "10",
    title: "건강한 식습관 형성",
    subtitle: "균형 잡힌 식단과 계획",
    description: "매일 10분간의 명상 세션을 통해 마음의 평화를 찾고 집중력을 높이세요.",
    image: "https://picsum.photos/seed/eating/600/400",
    category: "건강한 식습관",
    isUpcoming: true,
  },
];


export const AI_MESSAGES: AIMessage[] = [
    {
        id: 'msg1',
        type: 'critic',
        title: '또 딴짓했네. 목표 달성은 다음 생에 하려고?',
        content: '벌써 3시간째 유튜브만 보고 있잖아. 그 시간에 코딩 한 줄이라도 더 했으면 지금쯤 커밋 10개는 했겠다. 정신 안 차리면 도태되는 건 순식간이야.',
        timestamp: '2시간 전',
        goalId: '4',
        rotation: -1,
    },
    {
        id: 'msg2',
        type: 'praiser',
        title: '대단해! 오늘 목표 완벽하게 클리어했잖아!',
        content: '꾸준히 해내는 모습이 정말 멋져. 스스로에게 작은 선물이라도 해주는 거 어때? 이 기세로 내일도 화이팅이야! 넌 뭐든지 할 수 있어.',
        timestamp: '1시간 전',
        goalId: '2',
        rotation: 1,
    },
    {
        id: 'msg3',
        type: 'critic',
        title: '그렇게 대충 할 거면 시작도 하지 마.',
        content: '방금 제출한 보고서 말이야. 오탈자 천지에 논리도 엉망이던데? 다시 검토하고 제대로 만들어서 제출해. 프로는 결과로 말하는 거야.',
        timestamp: '30분 전',
        goalId: '3',
        rotation: 1,
    },
    {
        id: 'msg4',
        type: 'praiser',
        title: '와, 아이디어 진짜 반짝이는데?',
        content: '회의 때 냈던 아이디어, 다들 감탄했어. 역시 넌 그냥 평범한 사람이 아니라니까. 그 창의력, 앞으로도 계속 보여줘! 기대할게.',
        timestamp: '10분 전',
        goalId: '8',
        rotation: -2,
    },
    {
        id: 'msg5',
        type: 'critic',
        title: '벌써 자려고? 경쟁자들은 아직도 달리고 있어.',
        content: '성공은 편안한 잠자리에서 오지 않아. 남들보다 딱 한 시간만 더 집중해봐. 그 한 시간이 내일의 너를 바꿀 테니까.',
        timestamp: '방금 전',
        goalId: '5',
        rotation: -2,
    }
];
